<div>
    <div class="container-fluid">
        <div class="row"><div class="col-12"><div class="page-title-box"><h4 class="mb-sm-0 font-size-18">Mon profil</h4></div></div></div>
        @if (session()->has('message'))<div class="alert alert-success alert-dismissible fade show">{{ session('message') }}<button type="button" class="btn-close" data-bs-dismiss="alert"></button></div>@endif
        <div class="row">
            <div class="col-xl-6"><div class="card border-0 shadow-sm"><div class="card-body"><h5 class="card-title mb-3">Informations du compte</h5><form wire:submit.prevent="updateProfile"><div class="mb-3"><label class="form-label">Nom</label><input type="text" class="form-control" wire:model.live="name">@error('name') <span class="text-danger">{{ $message }}</span> @enderror</div><div class="mb-3"><label class="form-label">Email</label><input type="email" class="form-control" wire:model.live="email">@error('email') <span class="text-danger">{{ $message }}</span> @enderror</div><div class="mb-3"><label class="form-label">Photo de profil</label><input type="file" class="form-control" wire:model.live="photo">@error('photo') <span class="text-danger">{{ $message }}</span> @enderror</div><button class="btn btn-primary" type="submit" wire:loading.attr="disabled">Modifier le profil</button></form></div></div></div>
            <div class="col-xl-6"><div class="card border-0 shadow-sm"><div class="card-body"><h5 class="card-title mb-3">Changer le mot de passe</h5><form wire:submit.prevent="updatePassword"><div class="mb-3"><label class="form-label">Mot de passe actuel</label><input type="password" class="form-control" wire:model.live="current_password">@error('current_password') <span class="text-danger">{{ $message }}</span> @enderror</div><div class="mb-3"><label class="form-label">Nouveau mot de passe</label><input type="password" class="form-control" wire:model.live="password">@error('password') <span class="text-danger">{{ $message }}</span> @enderror</div><div class="mb-3"><label class="form-label">Confirmer</label><input type="password" class="form-control" wire:model.live="password_confirmation"></div><button class="btn btn-primary" type="submit">Changer le mot de passe</button></form></div></div></div>
        </div>
    </div>
</div>
