<div>
    <div class="container-fluid">
        <div class="row"><div class="col-12"><div class="page-title-box d-sm-flex align-items-center justify-content-between"><h4 class="mb-sm-0 font-size-18">Utilisateurs et roles</h4><button class="btn btn-primary" wire:click="createUser"><i class="fas fa-user-plus"></i> Ajouter utilisateur</button></div></div></div>
        @if (session()->has('message'))<div class="alert alert-success alert-dismissible fade show">{{ session('message') }}<button type="button" class="btn-close" data-bs-dismiss="alert"></button></div>@endif
        <div class="card border-0 shadow-sm"><div class="card-body">
            <div class="row g-2 mb-3"><div class="col-md-8"><input type="text" class="form-control" placeholder="Rechercher nom ou email..." wire:model.live.debounce.400ms="searchTerm"></div><div class="col-md-4"><select class="form-control" wire:model.live="roleFilter"><option value="">Tous les roles</option>@foreach($roleOptions as $value => $label)<option value="{{ $value }}">{{ $label }}</option>@endforeach</select></div></div>
            <div class="table-responsive"><table class="table table-bordered table-striped align-middle"><thead class="table-light"><tr><th>Nom</th><th>Email</th><th>Role</th><th>Date creation</th><th>Actions</th></tr></thead><tbody>@forelse($users as $user)<tr><td>{{ $user->name }}</td><td>{{ $user->email }}</td><td><span class="badge bg-primary">{{ $roleOptions[$user->role] ?? $user->role }}</span></td><td>{{ $user->created_at->format('d/m/Y') }}</td><td><div class="btn-group"><button class="btn btn-sm btn-warning" wire:click="editUser({{ $user->id }})"><i class="fas fa-edit"></i></button><button class="btn btn-sm btn-danger" wire:click="deleteUser({{ $user->id }})"><i class="fas fa-trash"></i></button></div></td></tr>@empty<tr><td colspan="5" class="text-center text-muted">Aucun utilisateur.</td></tr>@endforelse</tbody></table>{{ $users->links('livewire::bootstrap') }}</div>
        </div></div>
        <div class="modal fade" id="userModal" tabindex="-1" wire:ignore.self><div class="modal-dialog modal-lg"><div class="modal-content"><div class="modal-header"><h5 class="modal-title">{{ $editMode ? 'Modifier utilisateur' : 'Ajouter utilisateur' }}</h5><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><form wire:submit.prevent="{{ $editMode ? 'updateUser' : 'addUser' }}"><div class="modal-body"><div class="row"><div class="col-md-6 mb-3"><label class="form-label">Nom *</label><input type="text" class="form-control" wire:model.live="name">@error('name') <span class="text-danger">{{ $message }}</span> @enderror</div><div class="col-md-6 mb-3"><label class="form-label">Email *</label><input type="email" class="form-control" wire:model.live="email">@error('email') <span class="text-danger">{{ $message }}</span> @enderror</div></div><div class="row"><div class="col-md-6 mb-3"><label class="form-label">Role *</label><select class="form-control" wire:model.live="role">@foreach($roleOptions as $value => $label)<option value="{{ $value }}">{{ $label }}</option>@endforeach</select>@error('role') <span class="text-danger">{{ $message }}</span> @enderror</div><div class="col-md-6 mb-3"><label class="form-label">Mot de passe {{ $editMode ? '(laisser vide pour conserver)' : '*' }}</label><input type="password" class="form-control" wire:model.live="password">@error('password') <span class="text-danger">{{ $message }}</span> @enderror</div></div></div><div class="modal-footer"><button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Fermer</button><button type="submit" class="btn btn-primary">{{ $editMode ? 'Modifier' : 'Enregistrer' }}</button></div></form></div></div></div>
    </div>
</div>
@push('scripts')
<script>document.addEventListener('livewire:initialized',()=>{Livewire.on('openUserModal',()=>new bootstrap.Modal(document.getElementById('userModal')).show());Livewire.on('userSaved',()=>bootstrap.Modal.getInstance(document.getElementById('userModal'))?.hide());});</script>
@endpush
